# Generated by Django 5.2.7 on 2025-10-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='github_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
