# Generated by Django 5.2.7 on 2025-10-07 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_avatar_url_customuser_github_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='github_id',
        ),
    ]
